### ISSUE TITLE
Sensor returning "UNKNOWN" but data is extracting when API is queried directly

### ISSUE THREAD

**Issue by DisneyMikeNZ** [make-all/metlink-nz#10] opened 2024-05-04 11:11 UTC
Hi there. I've recently noticed that my sensor for tracking the trains running from PAEK to WELL has started reporting as unknown. It has been running fine for the last 2 years, and I would blame an update to HA, but it's the only metlink sensor that's not working...

**What works:**
- My sensors for PAEK>WAIK and WELL>PAEK are working as expected in HomeAssistant.
- Querying the API directly through the Metlink Developer Portal preview and from Terminal via the provided curl script.

I've attached a screenshot of the Dev Portal, and the current sensor behaviour.

There are also errors being reported in the HA logs (I've attached a screenshot of the top level entry, but if you need more detail I'm happy to get it out for you).

Thank you for providing a very niche but _very useful_ add-on!

<img width="1417" alt="Screen Shot 2024-05-04 at 11 07 06 PM" src="https://github.com/make-all/metlink-nz/assets/88962350/25197982-f518-490c-bbd2-85f77be9a4bc">
<img width="588" alt="Screen Shot 2024-05-04 at 11 08 25 PM" src="https://github.com/make-all/metlink-nz/assets/88962350/9ffe5471-867b-4c35-8b3d-dc92c242d8f5">
<img width="1669" alt="Screen Shot 2024-05-04 at 11 07 28 PM" src="https://github.com/make-all/metlink-nz/assets/88962350/2f7e1178-f341-4bf7-b8a7-40af9a1a7e68">

**Comment by line-nz** [comment] 2024-05-07 21:06
I had this a month ago and fixed it by deleting and recreating the config within the Metlink integration

**Comment by make-all** [comment] 2024-05-07 22:39
I'm no longer living in Wellington, so forgive me for the stupid question. Was there recently a long period without train service?

Normally the next morning's departures will already be available when the last departure leaves, but the log message when it went unavailable seems to suggest that no departures were listed.  Still, it should become available again when there are departures.

**Comment by make-all** [comment] 2024-05-07 22:41
It would maybe help to see the full details of that last Error message for PAEK.  Does it expand if you click on it?

**Comment by make-all** [comment] 2024-05-07 22:44
The returned data is mentioning stop ids of PAEK2 and WELL1, which seems to be a recent change they have made.  Maybe you will get better results from using those instead?

This was actually a recent change another user submitted to the [README](https://github.com/make-all/metlink-nz/pull/9/files)

**Comment by DisneyMikeNZ** [comment] 2024-05-16 06:55
Sorry for the delay - only just getting a chance to respond now. Thank you for responding @make-all, especially since you've left the area and this is currently of no benefit to yourself :)

> It would maybe help to see the full details of that last Error message for PAEK. Does it expand if you click on it?

This is what I get:
```
This error originated from a custom integration.

Logger: custom_components.metlink.sensor
Source: custom_components/metlink/sensor.py:197
integration: Metlink Wellington Transport (documentation, issues)
First occurred: 6:21:04 AM (28 occurrences)
Last logged: 6:35:21 PM

Error retrieving data from Metlink API for sensor Metlink WELL.
Error retrieving data from Metlink API for sensor Metlink PAEK.
Traceback (most recent call last):
  File "/config/custom_components/metlink/sensor.py", line 197, in async_update
    data = await self.metlink.get_predictions(self.stop_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metlink/MetlinkAPI.py", line 49, in get_predictions
    r.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.opendata.metlink.org.nz/v1/stop-predictions?stop_id=WELL')
```

> The returned data is mentioning stop ids of PAEK2 and WELL1, which seems to be a recent change they have made. Maybe you will get better results from using those instead?
> 
> This was actually a recent change another user submitted to the [README](https://github.com/make-all/metlink-nz/pull/9/files)

Replacing the destination with `WELL1` **appears to have fixed it**, thank you.

> I'm no longer living in Wellington, so forgive me for the stupid question. Was there recently a long period without train service?
> 
> Normally the next morning's departures will already be available when the last departure leaves, but the log message when it went unavailable seems to suggest that no departures were listed. Still, it should become available again when there are departures.

There are no dumb questions! There's been a higher incidence of busses replacing trains, but that's mostly late nights and weekends. My HAs host restarts at 5am each morning (don't judge me, the hardware has a tendency to hang after a while and I can't be bothered investigating and resolving it haha), so it's entirely possible that this timing could be part of the problem, but it never used to occur (at least not that I noticed).

> I had this a month ago and fixed it by deleting and recreating the config within the Metlink integration

Good to know @line-nz, I'll keep that in mind if it does it again, thank you.

**Comment by make-all** [comment] 2024-05-16 21:50
It seems the problem is solved by changing from `WELL` to `WELL1`, so I will close this, as a documentation update was already made to highlight this.

**Closed as completed by make-all** 2024-05-16 21:50 UTC
